kind: project
metadata:
  name: unlockpa-mlrun
  created: '2023-10-02T08:31:04.000885'
spec:
  functions:
  - url: data-prep.py
    name: data-prep
    kind: job
    image: mlrun/mlrun
    handler: breast_cancer_generator
  - url: faq-prep.py
    name: faq-prep
    kind: job
    image: mlrun/mlrun
    handler: parse_faq_excel
    with_repo: true
  - url: faq-train.py
    name: faq-trainer
    kind: job
    image: mlrun/mlrun
    handler: train_faq_caseclus
    with_repo: true
  workflows: []
  artifacts: []
  conda: ''
  source: git://kazhamiakin@github.com/kazhamiakin/unlockpa.git#main
  origin_url: git://kazhamiakin@github.com/kazhamiakin/unlockpa#main
  load_source_on_run: true
  desired_state: online
  build:
    commands: []
    requirements: []
  custom_packagers: []
status:
  state: online
